export const AUTH_STARTED = "AUTH_STARTED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GAME_FETCHED = "GAME_FETCHED";
export const GAME_FETCH_STARTED = "GAME_FETCH_STARTED";
export const GAME_FETCH_FAILED = "GAME_FETCH_FAILED";

export const CREATE_GAME = "CREATE_GAME";
export const CREATE_GAME_ASYNC = "CREATE_GAME_ASYNC";

export const SOCKET_INITIATED = "SOCKET_INITIATED";

export const SOCKET_CLOSED = "SOCKET_CLOSED";

export const TABLE_MESSAGE_FETCHED = "TABLE_MESSAGE_FETCHED";
export const CLEAR_TABLE_MESSAGE = "CLEAR_TABLE_MESSAGE"
export const CHAT_FETCHED = "CHAT_FETCHED";

export const J_DROPPED = "J_DROPPED";
export const J_CHOSEN = "J_CHOSEN";

export const PLAYER_INPUT_REQUIRED_FOR_EIGHT =
  "PLAYER_INPUT_REQUIRED_FOR_EIGHT";
export const PLAYER_INPUT_GIVEN_FOR_EIGHT = "PLAYER_INPUT_GIVEN_FOR_EIGHT";

export const PLAYER_INPUT_REQUIRED_FOR_JACK = "PLAYER_INPUT_REQUIRED_FOR_JACK";
export const PLAYER_INPUT_GIVEN_FOR_JACK = "PLAYER_INPUT_GIVEN_FOR_JACK";

export const PLAYER_INPUT_REQUIRED_FOR_SAME_RANK_OR_SUIT =
  "PLAYER_INPUT_REQUIRED_FOR_SAME_RANK_OR_SUIT";
export const PLAYER_INPUT_GIVEN_FOR_SAME_RANK_OR_SUIT =
  "PLAYER_INPUT_GIVEN_FOR_SAME_RANK_OR_SUIT";

export const CHAT_FETCH_STARTED = "CHAT_FETCH_STARTED";
export const CHAT_FETCH_FAILED = "CHAT_FETCH_FAILED";
export const NEW_CHAT_RECIEVED = "NEW_CHAT_RECIEVED";
export const RESET_NEW_CHAT = "RESET_NEW_CHAT";

export const END_GAME_REQUESTED = "END_GAME_REQUESTED";
export const PLAYER_LEAVE_GAME_REQUESTED = "PLAYER_LEAVE_GAME_REQUESTED";
export const LEAVE_GAME = "LEAVE_GAME";
export const RESET_LEAVE_GAME = "RESET_LEAVE_GAME";
export const END_GAME_CLOSED = "END_GAME_CLOSED";
export const PLAYER_LEAVE_GAME_CLOSED = "PLAYER_LEAVE_GAME_CLOSED";
